---
- name: Gather information from routers
  hosts: arista
  gather_facts: false

- name: Retrieve eos facts 
  arista.eos.vlans:
    state: gathered
  register: intffacts
        
- name: print out interfaces
  debug:
    var: intffacts
