---
- name: Gather information from routers
  hosts: arista
  gather_facts: false

  tasks:
    - name: Retrieve eos facts 
      arista.eos.interfaces:
        state: gathered
      register: intffacts
        
    - name: print out interfaces
      debug:
        var: intffacts
