---
- name: gather information from routers
  hosts: network
  gather_facts: no

  tasks:
    - name: gather Cisco router facts
      cisco.ios.facts:

    - name: gather Arista router facts
      arista.eos.facts:

    - name: display version
      debug:
        msg: "The OS version is: {{ ansible_net_version }}"
      
    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
   
